server:
  port: 8009  #端口配置
spring:
  redis: #redis参数配置
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
logging:
  level:
    cn.liulingfengyu.websocket: debug  #日志级别
  file:
    path: /opt/app/log #日志输出路径