server:
  port: 8010  #端口配置
spring:
  data:
    redis:
      port: 6379
      database: 0
      password: 123456
      host: 127.0.0.1
logging:
  level:
    cn.liulingfengyu.websocket: debug  #日志级别
  file:
    path: log #日志输出路径